### ISSUE TITLE
这是怎么回事？

### ISSUE THREAD

**Issue by ghost** [littlewin-wang/littlewin.server#8]
3babel presets path = /home/ziming/123/littlewin.server/node_modules/_runkoa@1.5.9@runkoa/node_modules
/home/ziming/123/littlewin.server/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /home/ziming/key/littlewin-server: Unexpected token, expected ; (2:8)
  1 | {
> 2 |   "AUTH": {
    |         ^
  3 |     "default": {
  4 |       "name": "*****",    // 默认账号,自行设置         
  5 |       "password": "*****" // 默认密码,自行设置
    at Parser.pp$5.raise (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:2236:8)
    at Parser.pp$1.parseStatement (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1911:17)
    at Parser.pp$1.parseBlockBody (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1868:19)
    at Parser.pp$1.parseBlockBody (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1778:8)
    at Parser.parse (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:1673:17)
    at parse (/home/ziming/123/littlewin.server/node_modules/_babylon@6.18.0@babylon/lib/index.js:7305:37)
    at File.parse (/home/ziming/123/littlewin.server/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/home/ziming/123/littlewin.server/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:602:20)
    at /home/ziming/123/littlewin.server/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/home/ziming/123/littlewin.server/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:564:16)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ghost** [comment]
解决了
