### ISSUE TITLE
这是什么错误？

### ISSUE THREAD

**Issue by ghost** [littlewin-wang/littlewin.server#9]
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/run`
3babel presets path = /home/ziming/123/littlewin.server/node_modules/_runkoa@1.5.9@runkoa/node_modules
module.js:634
    throw err;
    ^

SyntaxError: /home/ziming/key/littlewin-server.json: Unexpected token / in JSON at position 57
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:631:27)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/littlewin.server/config/env.js:16:54)
    at Module._compile (module.js:612:30)
    at loader (/home/ziming/123/littlewin.server/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ziming/123/littlewin.server/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:154:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ghost** [comment]
解决了
